Repository omerakben/itinerary-planning-fe, pull requests merged in 2025-02, with the labels that each got.

#43 My itinenaries Page
  src/app/page.js
  src/app/trips/page.js
  src/components/TripCard.js
  src/styles/globals.css
Labels: FE

#46 Search Functionaitly;
  src/app/trips/page.js
  src/components/NavBar.js
Labels: enhancement, FE

#52 Bug fix on edit form travel modes
  src/components/TripCard.js
  src/components/forms/TripForm.js
Labels: bug, FE

#57 Refactor TripForm component and add travel mode icons
  src/api/locationsData.js
  src/api/tripsData.js
  src/api/usersData.js
  src/app/layout.js
  src/app/profile/page.js
  src/app/trips/[id]/page.js
  src/app/trips/edit/[id]/page.js
  src/app/trips/new/page.js
  src/app/trips/page.js
  src/components/Icons.js
  src/components/ProtectedRoute.js
  src/components/forms/TripForm.js
  src/utils/context/ClientProvider.js
  src/utils/context/ViewDirector.js
  src/utils/context/authContext.js
Labels: bug
